// HTTP Requests for RenalRoutes.kt
###
GET http://localhost:8080/communityUsers
Content-Type: application/json

###
GET http://localhost:8080/communityUsers/1
Content-Type: application/json

###
POST http://localhost:8080/communityUsers
Content-Type: application/json

{
  "communityId": 1,
  "userId": 1,
  "isAdmin": true
}

###
PUT http://localhost:8080/communityUsers/1
Content-Type: application/json

{
  "communityId": 1,
  "userId": 1,
  "isAdmin": false
}

###
DELETE http://localhost:8080/communityUsers/2
Content-Type: application/json



